
[[Title]]
= `Zfinx` ISA Specification Addendum
Version 0.1
:doctype: book
:encoding: utf-8
:lang: en
:toc: left
:toclevels: 4
:numbered:
:xrefstyle: short
:le: &#8804;
:rarr: &#8658;

== Addendum update history

|===================================================================
| version | change
| 0.10    | initial version
|===================================================================


[[Heading]]
== Overview

This document gives additional information about `Zfinx` which is not included in the ISA specification.

[[Heading]]
== Discovery

If any `Zfinx` extension is specified then the compiler will have the following *#define* set:

`__riscv_zfinx`

So software can use this to choose between `Zfinx` or normal versions of floating point code.

Non-privileged code can detect whether `Zfinx` is implemented as follows:

[source,sourceCode,text]
----

li a0, 0 # set a0 to zero

#ifdef __riscv_zfinx

fneg.s a0, a0 # this will invert a0

#else

fneg.s fa0, fa0 # this will invert fa0

#endif

----

If `a0` is non-zero then it’s a `Zfinx` core, otherwise it’s a `non-Zfinx` core. Both branches result in the *same encoding*, but the assembly syntax is different for each variant.

[[assembly-syntax-and-code-porting]]
== Assembly Syntax and Code Porting

Any references to `F` registers, or removed instructions will cause assembler errors.

For example, the encoding for:

`FMADD.S <1>, <2>, <3>, <4>`

will disassemble and execute as:

`FMADD.S f1, f2, f3, f4`

on a non-`Zfinx` core, or:

`FMADD.S x1, x2, x3, x4`

on a `Zfinx` core.


_We considered allowing pseudo-instructions for the deleted instructions for easier code porting. For example allowing FLW to be a pseudo-instruction for LW, but decided not to. Because the register specifiers must change to integer registers, it makes sense to also remove the use of FLW etc. In this way the user is forced to rewrite their code for a `Zfinx` core, reducing the chance of undiscovered porting bugs. This only affects assembly code, high level language code is unaffected as the compiler will target the correct architecture._

[[modifications]]
== Modifications from extensions to the `Zfinx` versions

Because all floating point loads, stores and floating point to/from integer moves are removed on `Zfinx` cores, the following sections show the deleted instructions and give suggested replacements to get the same semantics.

[NOTE]

  Where a floating point load loads fewer than `XLEN` bits software NaN-boxing in software is required to get the same semantics as a non-`Zfinx` core. This is specified for consistency but is unlikely to be necessary. The compiler should *not* NaN-box in software as there is no reason to do so. Assembly writers can choose whether to NaN-box in software to give better error detection.

[NOTE]

  Where a floating point move moves fewer than `XLEN` bits then either sign extension (if the target is an `X` register) or NaN-boxing (if the target is an `F` register) is required in software to get the same semantics.

[[f-to-zfinx]]
=== Modifications from `F` to `Zfinx`

The modifications to the ISA of the `F` extension are shown in  <<F-replacements>>.

[[F-replacements]]
.replacements for `F` extension floating point load/store/move instructions
[width=100%,options="header",]
|=============================================================================
|*Instruction* |*RV32_Zfinx*|*RV64_Zfinx*

|              2+|*replacement to get the same semantics*

|FLW **f**rd, offset(xrs1)   |LW     |LW[U] and NaN-box in software 
|C.FLW[SP] **f**rd, uimm(x2)   |C.LW[SP] |C.LW[SP] and NaN-box in software 

|FSW **f**rd, offset(xrs1)   |SW     |SW 
|C.FSW[SP] **f**rd, uimm(x2)   |C.SW[SP] |C.SW[SP] 

|FMV.X.W xrd, **f**rs1 |MV |MV and sign extend in software 
|FMV.W.X **f**rd, xrs1 |MV |MV and NaN-box in software 

|=============================================================================

[[D-to-Zdinx]]
=== Modifications from `D` to `Zdinx`

The modifications to the ISA of the `D` extension are shown in  <<D-replacements>>.

[[D-replacements]]
.replacements for `D` extension floating point load/store/move instructions
[width=100%,options="header",]
|=============================================================================
|*Instruction* |*RV32_Zdinx*|*RV64_Zdinx*
|              2+|*replacement to get the same semantics*

|FLD **f**rd, offset(xrs1)   |LW,LW  |LD
|C.FLD[SP] **f**rd, uimm(x2)   |C.LW[SP], C.LW[SP] |C.LD[SP] 

|FSD **f**rd, offset(xrs1)   |SW,SW         |SD 
|C.FSD **f**rd, offset(xrs1) |C.SW,C.SW     |C.SD 
|C.FSD[SP] **f**rd, uimm(x2)   |C.SW[SP],C.SW[SP] |C.SD[SP]

|FMV.X.D xrd, **f**rs1 |FSGNJ.D xrd, xrs1, xrs1 |MV 
|FMV.D.X **f**rd, xrs1 |FSGNJ.D xrd, xrs1, xrs1 |MV 

|=============================================================================

[[Zfh-to-Zhinx]]
=== Modifications from `Zfh` to `Zhinx`

The modifications to the ISA of the `Zfh` extension are shown in  <<Zfh-replacements>>, in addition to <<F-replacements>>.

[[Zfh-replacements]]
.replacements for `D` floating point load/store/move instructions
[width=100%,options="header",]
|=============================================================================
|*Instruction* |*RV32_Zhinx*|*RV64_Zhinx*
|              2+|*replacement to get the same semantics*

|FLH **f**rd, offset(xrs1)   2+|LH[U] and NaN-box in software

|FSH **f**rd, offset(xrs1)   2+|SH

|FMV.X.H xrd, **f**rs1 2+|MV and sign extend in software
|FMV.H.X **f**rd, xrs1 2+|MV and NaN-box in software

|=============================================================================

==== Use of the B-extension

The B-extension is useful for sign extending and NaN-boxing.

To sign-extend using the B-extension:

`FMV.X.H rd, rs1`

is replaced by:

`SEXT.H rd, rs1`

Without the B-extension two instructions are required: shift left 16 places, then arithmetic shift right 16 places.

NaN boxing in software is more involved, as the upper part of the register must be set to 1. The B-extension is also helpful in this case.

`FMV.H.X a0, a1`

is replaced by:

`C.ADDI a2, zero, -1`

`PACK a0, a1, a2`

[[vector]]
== Possible vector version of Zfinx

If the vector TG decide to specify a `Zfinx` version of the vector extension, the following instructions would be deleted, and the integer versions would be used instead:

[vec-replacements]
.replacements for scalar floating point instructions
[width=100%,options="header",]
|=================================
|*Instruction* |*Integer version*
|vfmv.v.f | vmv.v.x
|vfmv.f.s | vmv.x.s
|vfmv.s.f | vmv.s.x
|vfmerge.vfm | vmerge.vxm
|=================================

Additionally, all instructions with `funct3=OPFVF` take the scalar floating point source from either a single or pair of `X` registers instead of a single `F` register.

[[gdb]]
== GDB

When using GDB on a `Zfinx` core, GDB must report `X` registers instead of `F` registers when disassembling floating point opcodes. No other changes are required.

[[abi]]
== ABI

The Zfinx ABI is being defined by the pSABI TG.

[[fp_configs]]
== Floating Point Configurations To Reduce Area

To reduce the area overhead of FPU hardware new configurations will make the `F[N]MADD.\*, F[N]MSUB.*` and `FDIV.\*, FSQRT.*`` instructions optional in hardware.

This argument already exists for RISCV:

`gcc -mno-fdiv`

This argument exists for other architectures (e.g. MIPs) but not for RISCV, so it needs to be added:

`gcc -mno-fused-madd`

To achieve this we break all current and future floating point extensions into four parts: `Z*base`, `Z*ma`, `Z*div` and `Z*ldstmv`. There is an `-inx` version of the first three.

[[fpconfigs]]
.floating point configurations
[cols=",",options="header",]
|============================================================
|Options       |Meaning
2+|*base ISA*
|Zfhbase       |Support half precision base instructions
|Zfbase        |Support single precision base instructions
|Zdbase        |Support double precision base instructions
|Zqbase        |Support quad precision base instructions
2+|*base ISA-in-x*
|Zfhbaseinx    |Support Zfinx half precision base instructions
|Zfbaseinx     |Support Zfinx single precision base instructions
|Zdbaseinx     |Support Zfinx double precision base instructions
|Zqbaseinx     |Support Zfinx quad precision base instructions
2+|*FMA*
|Zfhma         |Support half precision multiply-add 
|Zfma          |Support single precision multiply-add 
|Zdma          |Support double precision multiply-add 
|Zqma          |Support quad precision multiply-add 
2+|*FMA-in-x*
|Zfhmainx      |Support Zfinx half precision multiply-add 
|Zfmainx       |Support Zfinx single precision multiply-add 
|Zdmainx       |Support Zfinx double precision multiply-add 
|Zqmainx       |Support Zfinx quad precision multiply-add 
2+|*FDIV*
|Zfhdiv        |Support half precision divide/square-root
|Zfdiv         |Support single precision divide/square-root
|Zddiv         |Support double precision divide/square-root
|Zqdiv         |Support quad precision divide/square-root
2+|*FDIV-in-x*
|Zfhdivinx     |Support Zfinx half precision divide/square-root
|Zfdivinx      |Support Zfinx single precision divide/square-root
|Zddivinx      |Support Zfinx double precision divide/square-root
|Zqdivinx      |Support Zfinx quad precision divide/square-root
2+|*load/store/move, incompatible with -inx options*
|Zfhldstmv     |Support load,store and integer to/from FP move 
|Zfldstmv      |Support load,store and integer to/from FP move 
|Zdldstmv      |Support load,store and integer to/from FP move 
|Zqldstmv      |Support load,store and integer to/from FP move 
|============================================================

Therefore:

* `RV32F` can be expressed as `RV32_Zfbase_Zfma_Zfdiv_Zfldstmv`.
* `RV32D` can be expressed as `RV32_Zfbase_Zfma_Zfdiv_fldstmv_Zdbase_Zdma_Zddiv_Zdldstmv`.
* `RV32_Zfinx` can be expressed as `RV32_Zfbaseinx_Zfmainx_Zfdivinx`.
* `RV32_Zdinx` can be expressed as `RV32_Zfbaseinx_Zfmainx_Zfdivinx_Zdbaseinx_Zdmainx_Zddivinx`.

If any `-inx` extension is specified, then all extensions from <<fpconfigs>> must have an `-inx` suffix.
The options are all additive, none of them remove or change instructions.


[[rationale]]
== Rationale, why implement `Zfinx`?

`Zfinx` allows small embedded cores to support floating point with:

* Minimal area increase
** `RV32I_Zfinx` saves 1/2 the register file state compared to `RV32IF`.
** `RV32E_Zfinx` saves 2/3 the register file state compared to `RV32EF`.
* Similar context switch time as an integer only core
** there are no `F` registers to save/restore
* Reduced code size by removing the floating point library
** Implementing floating point purely in software can be an expensive choice as the floating point library can be large, and expensive in terms of ROM or flash storage.
